/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: src/dds/GatewayData.h
  Source: /home/nvidia/gateway/idl/GatewayData.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_SRC_DDS_GATEWAYDATA_H
#define DDSC_SRC_DDS_GATEWAYDATA_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Gateway_DataType
{
  uint8_t data[4096];
  uint32_t length;
} Gateway_DataType;

extern const dds_topic_descriptor_t Gateway_DataType_desc;

#define Gateway_DataType__alloc() \
((Gateway_DataType*) dds_alloc (sizeof (Gateway_DataType)));

#define Gateway_DataType_free(d,o) \
dds_sample_free ((d), &Gateway_DataType_desc, (o))

typedef struct Gateway_CommandType
{
  uint8_t data[4096];
  uint32_t length;
} Gateway_CommandType;

extern const dds_topic_descriptor_t Gateway_CommandType_desc;

#define Gateway_CommandType__alloc() \
((Gateway_CommandType*) dds_alloc (sizeof (Gateway_CommandType)));

#define Gateway_CommandType_free(d,o) \
dds_sample_free ((d), &Gateway_CommandType_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_SRC_DDS_GATEWAYDATA_H */
