/**
 * @file app_config.c
 * @brief 配置管理系统实现
 */

#include "app_config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <strings.h>

/* 全局配置管理器 */
static ConfigManager g_config_instance;
ConfigManager *g_config_manager = NULL;

ConfigManager *config_get_global(void)
{
    return g_config_manager;
}

void config_set_global(ConfigManager *config)
{
    g_config_manager = config;
}

/* 去除字符串首尾空白 */
static char *str_trim(char *str)
{
    char *end;
    
    /* 去除前导空白 */
    while (isspace((unsigned char)*str)) {
        str++;
    }
    
    if (*str == '\0') {
        return str;
    }
    
    /* 去除尾部空白 */
    end = str + strlen(str) - 1;
    while (end > str && isspace((unsigned char)*end)) {
        end--;
    }
    end[1] = '\0';
    
    return str;
}

/* 查找配置项 */
static ConfigItem *find_item(ConfigManager *config, const char *section, const char *key)
{
    for (int i = 0; i < config->item_count; i++) {
        if (strcmp(config->items[i].section, section) == 0 &&
            strcmp(config->items[i].key, key) == 0) {
            return &config->items[i];
        }
    }
    return NULL;
}

/* 添加或更新配置项 */
static int set_item(ConfigManager *config, const char *section, const char *key, 
                    const char *value)
{
    ConfigItem *item = find_item(config, section, key);
    
    if (item) {
        /* 更新已有项 */
        strncpy(item->value, value, CONFIG_MAX_VALUE_LEN - 1);
        item->value[CONFIG_MAX_VALUE_LEN - 1] = '\0';
    } else {
        /* 添加新项 */
        if (config->item_count >= CONFIG_MAX_ITEMS) {
            return -1;
        }
        
        item = &config->items[config->item_count];
        strncpy(item->section, section, CONFIG_MAX_SECTION_LEN - 1);
        item->section[CONFIG_MAX_SECTION_LEN - 1] = '\0';
        strncpy(item->key, key, CONFIG_MAX_KEY_LEN - 1);
        item->key[CONFIG_MAX_KEY_LEN - 1] = '\0';
        strncpy(item->value, value, CONFIG_MAX_VALUE_LEN - 1);
        item->value[CONFIG_MAX_VALUE_LEN - 1] = '\0';
        item->type = CONFIG_TYPE_STRING;
        
        config->item_count++;
    }
    
    return 0;
}

int config_init(ConfigManager *config, const char *file_path)
{
    if (!config || !file_path) {
        return -1;
    }
    
    memset(config, 0, sizeof(ConfigManager));
    strncpy(config->file_path, file_path, CONFIG_MAX_PATH_LEN - 1);
    config->file_path[CONFIG_MAX_PATH_LEN - 1] = '\0';
    config->is_loaded = 0;
    
    return 0;
}

void config_destroy(ConfigManager *config)
{
    if (config) {
        memset(config, 0, sizeof(ConfigManager));
    }
}

int config_load(ConfigManager *config)
{
    if (!config || !config->file_path[0]) {
        return -1;
    }
    
    FILE *fp = fopen(config->file_path, "r");
    if (!fp) {
        return -1;
    }
    
    char line[512];
    char current_section[CONFIG_MAX_SECTION_LEN] = {0};
    int line_num = 0;
    
    while (fgets(line, sizeof(line), fp)) {
        line_num++;
        char *p = str_trim(line);
        
        /* 跳过空行和注释 */
        if (*p == '\0' || *p == '#' || *p == ';') {
            continue;
        }
        
        /* 解析节名 [section] */
        if (*p == '[') {
            char *end = strchr(p, ']');
            if (end) {
                *end = '\0';
                strncpy(current_section, str_trim(p + 1), CONFIG_MAX_SECTION_LEN - 1);
                current_section[CONFIG_MAX_SECTION_LEN - 1] = '\0';
            }
            continue;
        }
        
        /* 解析键值对 key = value */
        char *eq = strchr(p, '=');
        if (eq) {
            *eq = '\0';
            char *key = str_trim(p);
            char *value = str_trim(eq + 1);
            
            /* 去除值两端的引号 */
            if (*value == '"' || *value == '\'') {
                char quote = *value;
                value++;
                char *end = strrchr(value, quote);
                if (end) {
                    *end = '\0';
                }
            }
            
            if (current_section[0] && key[0]) {
                set_item(config, current_section, key, value);
            }
        }
    }
    
    fclose(fp);
    config->is_loaded = 1;
    
    return 0;
}

int config_save(ConfigManager *config)
{
    if (!config || !config->file_path[0]) {
        return -1;
    }
    
    FILE *fp = fopen(config->file_path, "w");
    if (!fp) {
        return -1;
    }
    
    /* 写入文件头注释 */
    fprintf(fp, "# Gateway Configuration File\n");
    fprintf(fp, "# Auto-generated by ConfigManager\n\n");
    
    char current_section[CONFIG_MAX_SECTION_LEN] = {0};
    
    for (int i = 0; i < config->item_count; i++) {
        ConfigItem *item = &config->items[i];
        
        /* 写入节名 */
        if (strcmp(current_section, item->section) != 0) {
            strcpy(current_section, item->section);
            fprintf(fp, "\n[%s]\n", item->section);
        }
        
        /* 写入键值对 */
        fprintf(fp, "%s = %s\n", item->key, item->value);
    }
    
    fclose(fp);
    return 0;
}

int config_reload(ConfigManager *config)
{
    if (!config) {
        return -1;
    }
    
    /* 清空现有配置 */
    config->item_count = 0;
    config->is_loaded = 0;
    
    /* 重新加载 */
    return config_load(config);
}

int config_get_string(ConfigManager *config, const char *section, const char *key,
                      const char *default_value, char *out_value, size_t max_len)
{
    if (!config || !section || !key || !out_value) {
        if (default_value && out_value && max_len > 0) {
            strncpy(out_value, default_value, max_len - 1);
            out_value[max_len - 1] = '\0';
        }
        return -1;
    }
    
    ConfigItem *item = find_item(config, section, key);
    if (item) {
        strncpy(out_value, item->value, max_len - 1);
        out_value[max_len - 1] = '\0';
        return 0;
    }
    
    if (default_value) {
        strncpy(out_value, default_value, max_len - 1);
        out_value[max_len - 1] = '\0';
    }
    return -1;
}

int config_get_int(ConfigManager *config, const char *section, const char *key,
                   int default_value)
{
    char value[CONFIG_MAX_VALUE_LEN];
    
    if (config_get_string(config, section, key, NULL, value, sizeof(value)) == 0) {
        return atoi(value);
    }
    
    return default_value;
}

int config_get_bool(ConfigManager *config, const char *section, const char *key,
                    int default_value)
{
    char value[CONFIG_MAX_VALUE_LEN];
    
    if (config_get_string(config, section, key, NULL, value, sizeof(value)) == 0) {
        /* 支持 true/false, yes/no, 1/0 */
        if (strcasecmp(value, "true") == 0 || 
            strcasecmp(value, "yes") == 0 ||
            strcmp(value, "1") == 0) {
            return 1;
        }
        if (strcasecmp(value, "false") == 0 || 
            strcasecmp(value, "no") == 0 ||
            strcmp(value, "0") == 0) {
            return 0;
        }
    }
    
    return default_value;
}

float config_get_float(ConfigManager *config, const char *section, const char *key,
                       float default_value)
{
    char value[CONFIG_MAX_VALUE_LEN];
    
    if (config_get_string(config, section, key, NULL, value, sizeof(value)) == 0) {
        return (float)atof(value);
    }
    
    return default_value;
}

int config_set_string(ConfigManager *config, const char *section, const char *key,
                      const char *value)
{
    if (!config || !section || !key || !value) {
        return -1;
    }
    
    return set_item(config, section, key, value);
}

int config_set_int(ConfigManager *config, const char *section, const char *key,
                   int value)
{
    char buf[32];
    snprintf(buf, sizeof(buf), "%d", value);
    return config_set_string(config, section, key, buf);
}

int config_set_bool(ConfigManager *config, const char *section, const char *key,
                    int value)
{
    return config_set_string(config, section, key, value ? "true" : "false");
}

void config_print_all(ConfigManager *config)
{
    if (!config) {
        return;
    }
    
    printf("=== Configuration (%s) ===\n", config->file_path);
    printf("Total items: %d\n\n", config->item_count);
    
    char current_section[CONFIG_MAX_SECTION_LEN] = {0};
    
    for (int i = 0; i < config->item_count; i++) {
        ConfigItem *item = &config->items[i];
        
        if (strcmp(current_section, item->section) != 0) {
            strcpy(current_section, item->section);
            printf("[%s]\n", item->section);
        }
        
        printf("  %s = %s\n", item->key, item->value);
    }
    
    printf("===========================\n");
}
